FROM python:3.9
COPY src/3pc/agent/runners/evm/rpc_proxy/requirements.txt .
RUN pip3 install -r requirements.txt
COPY src/3pc/agent/runners/evm/rpc_proxy/ .
COPY scripts/wait-for-it.sh .
CMD ["python3","-u","rpc_proxy.py"]
